### ISSUE TITLE
How do i get the spinner selected item position..?

### ISSUE THREAD

**Issue by rubinnellikunnathu** [piotrek1543/CustomSpinner#1]

**Comment by piotrek1543** [comment]
did you tried  ` spinner1.getSelectedItemPosition(), as it explained in Android Developers Reference: http://developer.android.com/reference/android/widget/AdapterView.html#getSelectedItemPosition()

**Comment by piotrek1543** [comment]
@rubinnellikunnathu have you already found a solution? Was mine helpful?
