### ISSUE TITLE
How to set Font size

### ISSUE THREAD

**Issue by veersamrat** [piotrek1543/CustomSpinner#2]
Please can you explain how to set font size for custom spinner?

**Comment by piotrek1543** [comment]
Hi, 

this library is just an extension of typical `Spinner` view. Just explore StackOverflow answers to find the most suitable for you. If you want to change a font size for first (I mean 'promptText') or for selected item, try to use this code:

    private OnItemSelectedListener OnCatSpinnerCL = new AdapterView.OnItemSelectedListener() {
        public void onItemSelected(AdapterView<?> parent, View view, int pos, long id) {
    
           ((TextView) parent.getChildAt(0)).setTextColor(Color.BLUE);
           ((TextView) parent.getChildAt(0)).setTextSize(5);
    
        }
    
        public void onNothingSelected(AdapterView<?> parent) {
    
        }
    };

Hope it will help.
